### ISSUE TITLE
README.mdを書き直す

### ISSUE THREAD

**Issue by vvakame** [vvakame/prh#10]
後方参照問題とかコンフィグファイルの統合とかはだいたい解決してるので。
あ、でも後方参照のやつはリリースしてない…。

**Comment by azu** [comment]
関連ツールへのリンクもあると良さそう。

https://github.com/vvakame/language-review
とか、READMEだけみても実際にどういうサイクルで使うのか実感がわき辛いので、統合されたツールとかさらっと紹介した方がイメージしやすい気がします。

後、具体的扱えるファイルタイプがREADMEだけみるとよくわからなかったので(.reって何だろう？的な)、その辺もREADMEに案内が含まれてると実際に試してみようかなという感じになる気がします。

まあでもprhリポジトリを見に来るユースケースはルールの書き方と機能を見たい場合がメインだと思うので、その辺が詳しく書かれてるか 「このユースケースはこのサンプル見て」みたいのリンクがあると良さそうな気がします。

**Comment by vvakame** [comment]
ざっくり対応しました。
screencastみたいなのが欲しいような気も…。
