### ISSUE TITLE
expectedの値がpatternの値を含む場合、意図しない置換結果になる

### ISSUE THREAD

**Issue by orangain** [vvakame/prh#17]
## 環境

```
$ prh --version
1.0.0
```

## 問題

カタカナ語の末尾に長音をつけるように統一しようと思い、以下のルールを定義します。

```
$ cat prh.yml
version: 1
rules:
  - expected: サーバー
    pattern:  サーバ
```

以下のファイルを対象として、

```
$ cat sample.md
サーバのホスト名とポート番号を指定して、
サーバーに接続します。
```

prhを実行すると、以下のように意図せず`サーバー`が`サーバーー`に置換されてしまいます。

```
$ prh sample.md
サーバーのホスト名とポート番号を指定して、
サーバーーに接続します。
```

単純に置換したらこのようになるのは納得できますが、`サーバー`は`サーバー`のままで保持されると嬉しいです。

## 回避策

以下のようにパターンを変更すれば`サーバー`はそのまま保持されるので、現在はこのようにして回避しています。ただ、パターンが煩雑になるので、上記のような書き方ができると嬉しいです。

```
  - expected: サーバー
    pattern:  /サーバ(?!ー)/
```

## 参考

* [Report error correctly when pattern starts with expected value by orangain · Pull Request #8 · azu/textlint-rule-prh](https://github.com/azu/textlint-rule-prh/pull/8)

**Comment by vvakame** [comment]
ちょっと考えてみますが、基本は回避策で書いてある書き方を正規の運用と考えています。

**Comment by azu** [comment]
このケース結構質問されるので、
https://github.com/vvakame/prh/blob/master/misc/prh.yml のサンプルとしてあるといいのかもしれません。

**Comment by orangain** [comment]
わかりやすくていいですね！
