### ISSUE TITLE
同一のexpectedの値を持つルールが複数あるとルールが適用されない場合がある

### ISSUE THREAD

**Issue by orangain** [vvakame/prh#18]
## 環境

```
$ prh --version
1.0.0
```

## 問題

同一のexpectedの値を持つルールが複数ある設定ファイル`prh.yml`と、

```
$ cat prh.yml
version: 1
rules:
  - expected: ブラウザ
    pattern: /Webブラウザー?|WEBブラウザー?/

  - expected: ブラウザ
    pattern: ブラウザー
```

そのファイルをインポートする設定ファイル`import.yml`の2つを用意します。

```
$ cat import.yml
version: 1
imports:
   - ./prh.yml
```

サンプルの文章を用意します。

```
$ cat sample.md
Webブラウザを開き
ブラウザーの開発者ツールで要素を検証します。
```

`prh.yml`を使用した場合は、意図したとおり2つのルールが両方使われますが、

```
$ prh --rules prh.yml sample.md
ブラウザを開き
ブラウザの開発者ツールで要素を検証します。
```

`import.yml`を使用した場合は、2つ目のルールは使用されません。これは意図しない結果です。

```
$ prh --rules import.yml sample.md
ブラウザを開き
ブラウザーの開発者ツールで要素を検証します。
```

両者が異なる結果になるのは直感に反するので、同じ結果になるほうが良いと思います。または、同じファイルに同一のexpectedの値を持つルールが複数あることは認められないのであれば、ルールのロード時にエラーになると良いと思います。

## 参考

* https://github.com/azu/textlint-rule-web-plus-db/blob/1.1.5/dict/web%2Bdb_press.yml#L362-367

**Comment by vvakame** [comment]
yamlはJSONに置換可能なものであると考えておきたいので、エラーにするのが良さそうですね。

**Comment by vvakame** [comment]
yamlの構造を覚えてなかったけど普通にJSONで表現可能だった…
importsした時に1つしか有効ではないのは、半分意図したものでした。

本来の狙いは、importされるyamlで定義されている内容を上書き(失効)させたい場合、importするyamlに同名のexpectedがあった場合、する側の定義のみが生きるようにしたかったのでした。
これは、importされる側は固定のルールセット(ユーザが編集しない)であろうという想定に基きます。
importされる側を編集せずに挙動を変えたい場合の動作を考えたわけですね。

というのをコード読んで思い出しました。

**Comment by orangain** [comment]
遅くなりました :bow: 重複したルールをimportしてもそのまま有効になるようになったのですね。ありがとうございます！

今までimportされる側のルールを変更していましたが、importする側で上書きするのがあるべき姿だったのですね。今後は上書きするようにしてみます。
